// DOM lookup table for the static HTML shell.
function byId(id) {
    const element = document.getElementById(id);
    if (!element)
        throw new Error(`Missing required element: #${id}`);
    return element;
}
export const refs = {
    offlineBanner: byId("offlineBanner"),
    goldValue: byId("goldValue"),
    diamondValue: byId("diamondValue"),
    essenceValue: byId("essenceValue"),
    progressValue: byId("progressValue"),
    heroLevel: byId("heroLevel"),
    heroStatus: byId("heroStatus"),
    expValue: byId("expValue"),
    expBar: byId("expBar"),
    attackValue: byId("attackValue"),
    defenseValue: byId("defenseValue"),
    hpValue: byId("hpValue"),
    speedValue: byId("speedValue"),
    critValue: byId("critValue"),
    regenValue: byId("regenValue"),
    dpsValue: byId("dpsValue"),
    equipmentSlots: byId("equipmentSlots"),
    saveButton: byId("saveButton"),
    autoAdvanceToggle: byId("autoAdvanceToggle"),
    autoAdvanceWorldToggle: byId("autoAdvanceWorldToggle"),
    heroCardName: byId("heroCardName"),
    heroHpBar: byId("heroHpBar"),
    heroHpText: byId("heroHpText"),
    enemyTag: byId("enemyTag"),
    enemyName: byId("enemyName"),
    enemyHpBar: byId("enemyHpBar"),
    enemyHpText: byId("enemyHpText"),
    enemyPower: byId("enemyPower"),
    furyButton: byId("furyButton"),
    furyCooldown: byId("furyCooldown"),
    furyState: byId("furyState"),
    worldValue: byId("worldValue"),
    stageValue: byId("stageValue"),
    stageTypeValue: byId("stageTypeValue"),
    dungeonStateValue: byId("dungeonStateValue"),
    worldClearValue: byId("worldClearValue"),
    bossKillValue: byId("bossKillValue"),
    drawCountValue: byId("drawCountValue"),
    deathValue: byId("deathValue"),
    worldName: byId("worldName"),
    stageDescriptor: byId("stageDescriptor"),
    worldDescription: byId("worldDescription"),
    campaignBar: byId("campaignBar"),
    nextUnlockValue: byId("nextUnlockValue"),
    menuTabs: byId("menuTabs"),
    leaveDungeonButton: byId("leaveDungeonButton"),
    dungeonList: byId("dungeonList"),
    upgradeList: byId("upgradeList"),
    blessingList: byId("blessingList"),
    relicList: byId("relicList"),
    statusList: byId("statusList"),
    drawOneButton: byId("drawOneButton"),
    drawTenButton: byId("drawTenButton"),
    drawCategoryTabs: byId("drawCategoryTabs"),
    rateInfoButton: byId("rateInfoButton"),
    rateModal: byId("rateModal"),
    rateModalTitle: byId("rateModalTitle"),
    rateModalBody: byId("rateModalBody"),
    rateModalClose: byId("rateModalClose"),
    diamondMetaValue: byId("diamondMetaValue"),
    drawPityValue: byId("drawPityValue"),
    recentDraws: byId("recentDraws"),
    inventoryList: byId("inventoryList"),
    synthesisList: byId("synthesisList"),
    combatLog: byId("combatLog"),
};
